### ISSUE TITLE
Difference between "latest tracks" on /samro and /samro/tracks

### ISSUE THREAD

**Issue by SamuelRott** [internet4000/radio4000#93] opened 2017-09-13 15:40 UTC
Hey, 
I am coming back about this deleted tracks problem.

They are not deleted, i was mislead by the difference between "latest track" on /samro and the latest trarcks on /samro/tracks

the diff got solved after a few hard reload

Bu the diff created a strange behavior:

when you hit the play button of your radio on https://radio4000.com/ it plays the first track of /samro/tracks even if it his the third track in the player (my case before all the hard refresh)

**Comment by hugurp** [comment] 2017-09-13 16:31
(cp from the chat.)

if I udnerstand corerctly, I think the problem is that the player and the cms do not use the same "track cache"

getting the tracks in the player, and getting them in the cms (radio4000.com) is made in two different calls
 
so if you delete a track in your radio, and you are currently playing the radio, you will still see the deleted track in the current player session
 
if you refresh the page and play you radio again you won't see anymore this track as a new query to the db is made by the player
 
can it be this?

**Comment by SamuelRott** [comment] 2017-09-14 17:36
IDK if it is link to the "track cache".

Basically you can reproduce the behaviour by clicking the play button of my radio on https://radio4000.com/all.

the track playing will be
Ex Ovo . Crazy Nature (Germany 1971)

when the latest track is
Unitopia - The Garden

**Comment by oskarrough** [comment] 2017-09-14 18:20
I can reproduce and I don't get it…

**Comment by SamuelRott** [comment] 2017-09-14 18:23
you don't get what i expect, my explanation or the "bug" ? :D

**Comment by oskarrough** [comment] 2017-09-14 18:25
no the bug.. but now I have something:

If you refresh at https://radio4000.com/samro/ it is "Unitopia".
If you refresh at https://radio4000.com/samro/tracks, the latest track is "Ex Ovo".

If you go from /samro to /samro/tracks it'll merge the two track lists and you'll see "Unitopia" at top of /samro/tracks.

But whyy

**Comment by oskarrough** [comment] 2017-09-14 18:31
I just inspected the database, and the two Unitopia tracks are NOT saved in your `channel` but the tracks still exist (with a reference to your channel).

How can this happen again?

We could quickfix it by changing the loading on /samro/tracks to query all tracks BY channel. Right now we are querying all tracks FROM your channel. Hm..

**Comment by oskarrough** [comment] 2017-09-14 18:32
Do you remember trying to delete them or other leads?

**Comment by SamuelRott** [comment] 2017-09-15 13:28
I don't remember deleting the two Unitopia track. What i know is that i added them with the bookmark (but maybe this info will create more confusion).

I just added 2 tracks and the same behavior is happening, so i do not think is related to any delete action.

**Comment by oskarrough** [comment] 2017-09-15 14:36
were the two other tracks also through the bookmarklet?

**Comment by SamuelRott** [comment] 2017-09-15 14:39
yes, but i did not check if the behavior is different when a track is added in a different way.

**Comment by oskarrough** [comment] 2017-10-09 10:29
closing, think we fixed the deleting of tracks now. we can reopen if it happens again

**Closed by oskarrough** 2017-10-09 10:29 UTC
Labels: bug
